module.exports = {
  calculator: "🧮",
  result: "✅",
  warning: "⚠️",
  avatar: "🖼️",
  banner: "🏞️",
  server: "🌐",
  user: "👤",
  link: "<:emoji_11:1492034064163803196>",
  choose: "🎯",
  dice: "🎲",
  coin: "🪙",
  heads: "🙂",
  tails: "👑",
  sparkle: "✨",
  clock: "⏰",
  list: "📋",
  trash: "🗑️",
};